<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <script>
        let promise = new Promise(function (resolve, reject){
            setTimeout(()=> resolve("Success"), 2000);
        });
        // .then also returns a promise.
        // runs after the resolve.
        // promise.then(msg => console.log(msg))
        // .then(()=> console.log("This would be printed !"))
        // .then(()=> console.log("Even this gets printed"));

        promise.then(msg => {
            console.log(msg);
            throw new Error("Error")
        })
        // Do not break the chain. Nullify the error with the second function
        .then(
            ()=> console.log("this would be printed"),
            err => console.log(err), // Comment and Uncomment to see effect
        )
        .then(() => console.log("Even this gets printed !"))
        .catch(err => console.log(err)); // Stop on error. Do not nullify the error.

    </script>
</head>
<body>
    
</body>
</html>